### PR TITLE
RHEL7 systemd fix

### PR DESCRIPTION
**Pull request by coreone**
There is a bug in RHEL7 where systemd cannot determine enabled state without a static link when using templated services.  Therefore, I add the static link here if the service is enabled in RHEL7 so that Puppet won't try to re-enable the service on every run.

### CODE REVIEW

**Comment by edestecd** [comment]
Interesting.  Let me see if I can reproduce this in vagrant.

**Comment by coreone** [comment]
@edestecd did you need anything further on this?  I have tested it on several RHEL7 and CentOS7 VMs and it does seem to fix the issue we were seeing with clamav trying to be re-enabled on every Puppet run.

**Comment by coreone** [comment]
Closing this.  This seems to break RHEL7 until a systemd patch is integrated, so just forget this for now:
https://github.com/systemd/systemd/pull/3790

**Comment by edestecd** [comment]
Sorry for not getting to this sooner...
So is this fixed in systemd now and available in an updated rpm?

**Comment by coreone** [comment]
It is definitely *not* fixed in RHEL 7.2, so I would not recommend merging this PR any time soon.

**Comment by edestecd** [comment]
Were you still having the problem of puppet trying to re-enable the service on every run?
Or is everything OK now?

**Pull request closed without merging**
