### PR TITLE
Clamav milter tests

### PR DESCRIPTION
**Pull request by ubellavance**

### CODE REVIEW

**Comment by edestecd** [comment]
I have fixed the tests. Please rebase from master

**Comment by edestecd** [comment]
IT looks like this branch has both the spec tests and the added support for all oses.
I misunderstood yesterday when I asked you to make a separate PR for the tests.  Sorry.

You can do it in one PR if you prefer... Just rebase this one from master, if you like, and close the other.

**Comment by ubellavance** [comment]
I don't know how to rebase so I deleted my repo and created the file.  The tests don't pass and I don't know why, honestly.  The error message says `Evaluation Error: Error while evaluating a Function Call, Could not find class ::clamav-milter` and there is no occurence of clamav-milter in the new file.

**Comment by edestecd** [comment]
@ubellavance I was going to close and re open this PR to trigger the tests to run again, but it seems that the repository has been deleted, so it will not let me re open it.

**Pull request closed without merging**
