### PR TITLE
pdk convert run on the module

### PR DESCRIPTION
**Pull request by hdep**
here is the change needed for supporting pdk.

### CODE REVIEW

**Comment by hdep** [comment]
Hi @edestecd  still need to fix one last error. If you get any idea on how to fix this I would be more than happy to implement it !

**Comment by hdep** [comment]
Yay ! I did it :) 
Hope this helps !

**Comment by hdep** [comment]
Hi @edestecd  any chance to review this PR soon ? 
thanks !

**Comment by hdep** [comment]
Hi @edestecd do you have any update for this ?

**Comment by hdep** [comment]
Hi @edestecd any chance to have this PR validated ?

**Comment by hdep** [comment]
Hi, are you still interested by this ?

**Comment by edestecd** [comment]
@hdep yes sorry. I've been pretty busy with other things lately. I'll try and get this module moving again soon

**Comment by hdep** [comment]
Hi, any news on this ?

**Comment by edestecd** [comment]
We are updating puppet soon so I suspect I will need to spend some time on this very soon

**Pull request merged**
