### PR TITLE
Adding option to set specific version number for package installs

### PR DESCRIPTION
**Pull request by proofpoint-mlariz**
We have a need to be able to specify the package version that gets installed, and I imagine others may like to have reliabile and reproducible confidence this gives as well.

### CODE REVIEW

**Comment by edestecd** [comment]
I'm not sure why the build was not failing before you made this change.
Its related to strict variables being set.  `freshclam_package` is not being set for RedHat, I think.
Again, it should have been failing before, but would you mind explicitly setting it to `undef`.
I think that should fix it.

**Comment by proofpoint-mlariz** [comment]
obviously inherits is breaking more than fixing (only needed to fix spec tests)

**Comment by edestecd** [comment]
I saw another repo that mentioned travis ci just fixed a bug recently that made strict variables work.
I'll play around with it and see what I can figure out.

**Comment by proofpoint-mlariz** [comment]
Ok this should do it other than the ones that are specified as 'undef' in the params.pp which I  am still trying to figure out how to properly instantiate

**Comment by proofpoint-mlariz** [comment]
Ok seems this can't be fixed in spec file.
I am pretty sure that the UNDEF value is being passed, but when it hits the puppet manifest that determines that since it is undefined it should use '$clamav::freshclam_package' which isn't included as we are directly testing the freshclam.pp manifest.
I don't have what I would consider a "proper" fix. Only thing I can think of is to move from the top of those classes (freshclam.pp and user.pp) and declare within the class, making it pick '$clamav::freshclam_package' or fall back to undef. I'll commit this now to test.

**Comment by proofpoint-mlariz** [comment]
Upon reflection not sure how to do this and still allow it to be overwritten without ugly hackery which shouldn't be the method just to support passing a spec test. Thinking on this further

**Comment by edestecd** [comment]
How about just removing all you commits except the first one and then just changing
`STRICT_VARIABLES="no"` in .travis.yml

Then I can accept your merge request and have a look later....

**Pull request merged**
