### PR TITLE
no need to validate $groups if it is still undef

### PR DESCRIPTION
**Pull request by flyinbutrs**

### CODE REVIEW

**Comment by edestecd** [comment]
How about just removing the validation all together.
I think groups accepts a single group as well...

**Comment by edestecd** [comment]
@flyinbutrs what do you think of removing the validation on groups?

**Comment by flyinbutrs** [comment]
Yeah, I keep wanting to write super complicated multiple validations, but that's probably not worth it. I pushed an update to that effect.

**Comment by edestecd** [comment]
Great, thanks for the fix.  I totally overlooked it.

**Comment by edestecd** [comment]
Released to the the forge as version 0.3.1

**Pull request merged**
