### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by jlambert121**
These tests are not entirely comprehensive, but are a good start.

Done:
- Basic unit tests for gross functionality
- Initial acceptance tests, needs to be enhanced
- Passing acceptance tests for CentOS 6.5
- TravisCI config

Issues:  
- ubuntu-server-1204 beaker tests fails, clamav-daemon needs to be run with init provider, not upstart as detected
- Debian 7.8 acceptance tests wouldn't run - appears to be a beaker issue

I'm not going to have any time in the near future to look at these Debian/Ubuntu issues, but I will likely be submitting a PR to add CentOS7 support.

### CODE REVIEW

**Comment by jlambert121** [comment]
(Note this is based off of #9)

**Comment by edestecd** [comment]
I can handle the Debian/Ubuntu Issues

**Comment by edestecd** [comment]
Hmm, this includes changes from #9 as well.
I guess, since you based it off of your branch and not mine?
Is there a way to rebase and only get the test changes in this pr?

**Comment by edestecd** [comment]
Now that I have merged #9 that is...

**Pull request closed without merging**
