### PR TITLE
Add a class for scan job

### PR DESCRIPTION
**Pull request by hdep**
This class originally come from https://github.com/ucbpi/puppet-clamav/blob/master/manifests/scan.pp It allow to create a cron job in order to scan the whole server for virus. Very usefull for compliance.
I use it on Debian 8 and CentOS 7.
I think this code can be usefull for other people.

### CODE REVIEW

**Comment by hdep** [comment]
I just check the output of travis job : 
Network error while fetching

So I guess this is not related to my code.

@edestecd can you please have a look if you have time ? 

Thank you

**Comment by hdep** [comment]
Hi,

are you still working on this project @edestecd ?

Best regards

**Comment by edestecd** [comment]
@hdep yea I need to update this module for puppet 4/5 with pdk. I'll try to get to that in the next day or so.
Then you can rebase and hopefully the errors will go away.

**Comment by hdep** [comment]
great @edestecd, maybe I can try to help you out with pdk compatibility, I'll have a look.

**Comment by edestecd** [comment]
eck, work is killing me lately. Sorry. I'll try and get to it. But yea if you have time that would be great

**Comment by hdep** [comment]
Ok, I'll have a look. If you need more help to manage your great plugin you can ask to https://voxpupuli.org/

**Comment by hdep** [comment]
this PR is on my master branch so I'll need to close this and refork it if I wan't to try to convert to pdk...

**Pull request closed without merging**
