### PR TITLE
Added clamav-milter support

### PR DESCRIPTION
**Pull request by ubellavance**

### CODE REVIEW

**Comment by ubellavance** [comment]
@edestecd I see that this PR hasn't been merged yet, do you need anything from me?

**Comment by edestecd** [comment]
Can you rebase your branch please?  I'll give it a review after that and see if we can't get it in this week...

**Comment by ubellavance** [comment]
No problem!  But... I don't know how to do that, at all. As simple as that? https://github.com/blog/2243-rebase-and-merge-pull-requests

**Comment by edestecd** [comment]
Unfortunately there are conflicts, so you will have to do it on the command line and resolve the conflicts.  Try this:
```shell
cd puppet-clamav
git remote add upstream https://github.com/edestecd/puppet-clamav
git fetch upstream
git rebase upstream/master
# follow the prompts to correct conflicts
git push --force
```

**Comment by ubellavance** [comment]
It's not been trivial, but I did it.  Well, I did something, I hope it's right.  @edestecd please let me know if something's missing.

**Comment by edestecd** [comment]
This does not seem right. There are way too many commits. There should only be your new commits and not all these others. What commands did you run?

**Comment by ubellavance** [comment]
I didn't exit my shell and my computer started to swap a few hours later so I had to hard-reset it, so I don't have my shell history.  I remember having done this:

```
cd puppet-clamav
git remote add upstream https://github.com/edestecd/puppet-clamav => was not necessary
git fetch upstream
git rebase upstream/master
```
Then I remember having to choose a behaviour for git (simple vs matching?) Then I fixed conflicts by editing the files, leaving only what's good from all the changes and removing the <<<<< and >>>>> lines.  I remember that git push didn't work, but I can't remember if it was just doing nothing or if there was an error.  I remember having to do some `git add` commands. Sorry I can't remember any better. What can we do about it from this point?

**Comment by edestecd** [comment]
Hmm looks like a lot more than we wanted got added...
You could try a few things:

Option 1 (continue to use your current clone)
```shell
git fetch upstream
# make a new branch based off origin/master
git branch milter_support upstream/master
# switch to that branch
git checkout milter_support
# add back in your changes and make 1 commit
git push -u origin/milter_support
# add a new Pull request against milter_support
```

Option 2 (start over)
```shell
# set aside this copy
mv puppet-clamav puppet-clamav-old
# Delete your fork of clamav in Github web ui
# Re Fork edestecd/puppet-clamav
git clone <your url for ubellavance/puppet-clamav>
# add back in your changes and make 1 commit
git push -u origin/master
# see if this Pull Request updates / you may need to make a new one
```

**Comment by edestecd** [comment]
If you have specific commits you want, that you see here. You can reuse them with option 1.
Just do
```git cherry-pick <commit-hash>```
to transfer only those commits to the new branch.

**Comment by edestecd** [comment]
If you are successful your Pull Request will show only one or two selective commits that make the changes you want and nothing else.

**Comment by ubellavance** [comment]
1. You're amazing @edestecd.  Thanks for guiding me while i'm walking blind though this. Honestly, I'm only a basic SVN user, so I'm far from these concepts and actions (although I would love to help without needing to be helped myself.
2. I'll try to fix that mess soon.

**Comment by edestecd** [comment]
Any update? Can I help?

**Comment by ubellavance** [comment]
Hi @edestecd, thanks for offering your help.  I tried working on it but I find it extremely difficult to copy my edits in the new code.  I don't know if there are better tools than diff/fldiff but even though I changed only a few changes in one file and someone else changed a few lines, it showd me something like 100 changes, just because some lines are now at at different location in the file.

**Comment by ubellavance** [comment]
I've created a new PR. I hope it will work this time.  I successfully rebased my branch, inserted my edits and tested on my test system (starting with a fresh OS).

**Comment by ubellavance** [comment]
Follow-up in #30, closing.

**Pull request closed without merging**
